# -*- coding: utf-8 -*-
"""212_contains_duplicate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xv5iHkDHjSxykMxWn8fwIXJzEE00cZmJ

Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.
"""

class Solution:
    def containsDuplicate(self, nums: List[int]) -> bool:
        for i in range(len(nums)):
            for j in range(i+1,len(nums)):
                if nums[i]==nums[j]:
                    return True

class Solution:
    def hasDuplicate(self, nums: List[int]) -> bool:
        lst=set(nums)
        if len(lst)==len(nums):
            return False
        else:
            return True

class Solution:
    def hasDuplicate(self, nums: List[int]) -> bool:
        h_map={}
        for i in nums:
            if i in h_map:
                h_map[i]=h_map[i]+1
                if h_map[i]>1:
                    return True
            else:
                h_map[i]=1
        return False


